#! /bin/sh

### BEGIN INIT INFO
# Provides:             piappd
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    piapp autostart
### END INIT INFO

ifup eth0
mount -o uid=pi,gid=pi /dev/sda1 /var/www/html/piapp_output
cd /var/www/html/
xvfb-run piapp --plot_path piapp_output/output --out_path piapp_output/output --buffer_size 20 --plot_interval 10 >/dev/null 2>/dev/null &
/home/pi/offswitch.sh &

exit 0